### ISSUE TITLE
connect to another machine and local

### ISSUE THREAD

**Issue by icf20** [lidel/ipfs-firefox-addon#103]
hello, my questions if is there anyway to add a second machine that share the same ports and configuration?

**Comment by lidel** [comment]
Yes, one can install addon on multiple machines and point them all to use a single gateway on a specific IP and Port. It is perfectly fine.

Note that this one-time setup needs to be done manually (change default IP and ports) as there is no Preferences synchronization over Firefox Sync. (It can be added as an option, if there is such feature request).

**Comment by icf20** [comment]
what about the other way around ? :D if i got 2 machine running IPFS can I add them both ? 

the idea is to have one server shared whit some friends and each one using IPFS on their local machine

**Comment by lidel** [comment]
Not sure if I understand correctly. 

If you ask about having `go-ipfs`  running on a shared server and having multiple browsers with this addon set up to use it -- it is perfectly possible.  
Just keep in mind that API port should not be exposed to the internet so this setup makes sense only if you all are in the same LAN. If not, each of you should run your own instance of `go-ipfs`.

**Comment by icf20** [comment]
> Not sure if I understand correctly. 
> If you ask about having go-ipfs running on a shared server and having multiple browsers with this addon set up to use it -- it is perfectly possible

in addition to that the addon to connect to local machine not just the server

**Comment by lidel** [comment]
This scenario is possible:

- Add your server instance to the Public Gateway List of the addon
- Everyone runs their own local gateway and browser addon is set up to use it
- When someone opens a page from the remote gateway, addon redirects request to the local node

Is this what you had in mind?

**Comment by icf20** [comment]
imagine the next scenario
hash Q1234 is on the local machine then the add it works like now
hash Q4321 is on the server the browser loads from the server and the localhost does nothing 

does that make sense for you ?

**Comment by lidel** [comment]
No, sorry, I don't understand..

- update public gateway list and enable addon's redirect
- opening `fs:/ipfs/Q4321`  will load it from local IPFS node (if node does not have it in its local cache, then the resource will be fetched from IPFS)

What do you mean by "localhost does nothing"?

**Comment by icf20** [comment]
> What do you mean by "localhost does nothing"? Perhaps you could describe it in more detail.

because i already have the hash Q4321 i dont want this to be cached/storing on the local node

**Comment by lidel** [comment]
I am afraid the important point/side-effect of IPFS is to spread data cache over multiple nodes.

That being said, you can set cache size in `go-ipfs` config and/or periodically garbage collect unpinned objects via `ipfs repo gc`.

**Comment by icf20** [comment]
> I am afraid the important point/side-effect of IPFS is to spread data cache over multiple nodes.

not sure if the end user would like to have same data cached in multiple machines

**Comment by Kubuxu** [comment]
I would like, I frequently switch machines over, from PC to notebook to second notebook and only one machine is running at a time.

HDD storage is cheap, Internet bandwith is now but it is not a place for discussions about it.

**Comment by lidel** [comment]
Yup. I am locking this issue, but encourage further discussion in https://github.com/ipfs/faq/ :-)
