### ISSUE TITLE
Add Pale Moon support

### ISSUE THREAD

**Issue by KrzysiekJ** [lidel/ipfs-firefox-addon#147]
[Pale Moon browser](http://www.palemoon.org/) seems to be recognized by addons.mozilla.org as Firefox 24.9, hence no version of this addon is installable. It would be nice to somehow whitelist this browser, of course if it is supposed to be actually compatible. (Yes, I know that there is an ongoing process of porting to Web Extensions which will break compatibility fundamentally, but at least old versions will be working).

**Comment by lidel** [comment]
Unfortunately it is not enough to "just whitelist version X". 

Those version checks are there for a reason. Every new Firefox release introduces new APIs which are not present in older releases. One can use v1.2.0 of this add-on with Firefox 33, but v1.5.9 requires APIs that were introduced in FF 43.  

Just to be sure it does not "just work", I tried to run several versions of the add-on against PaleMoon 26.4.1.

Nothing works. Even the old v1.1.0 (last release built with CFX before moving to JPM) produces errors:

```
Error: Module `sdk/ui/button/toggle` is not found at resource://gre/modules/commonjs/sdk/ui/button/toggle.js
```

Well, at least we checked :-)
