### ISSUE TITLE
Incorrect notification of PIN failure

### ISSUE THREAD

**Issue by paul90** [lidel/ipfs-firefox-addon#148]
When using the IPFS docker image (tag v.0.4.3) requesting "Pin IPFS Resource" always show a notification that the pin failed.

Using `ipfs pin ls` before and after making the pin request shows that the request worked, even though this addon gives a notification that it failed.

(Firefox version 49.0 - OS/X 10.11.6 - e10s disabled)

**Comment by lidel** [comment]
Thank you for reporting this! 

Seems that the JSON returned in response changed at some point. 
I made it work in both old and new versions. Will release bugfix in 1.5.10.

**Comment by lidel** [comment]
Just FYI version `2.x.x` ([under development](https://github.com/lidel/ipfs-firefox-addon/milestone/3)) will use [js-ipfs-api](https://github.com/ipfs/js-ipfs-api) library as an abstraction for accessing HTTP API, which will remove surface for this class of errors. :ok_hand:

**Comment by paul90** [comment]
Thank you for the update
