### ISSUE TITLE
Local HTTP2IPFS without gateways

### ISSUE THREAD

**Issue by RndFooBar** [lidel/ipfs-firefox-addon#149]
From [this][1] reddit thread:

[1]: https://www.reddit.com/r/ipfs/comments/545jky/a_possible_alternative_approach_to_local_http2ipfs

> So I don't know if this is the right place to post this, but I hope that you could share your opinion with me regarding my proposition.
>
> # The Current Situation:
> 
> If a webmaster tries to create a website with static assets (images, javascript, css, ...) that they want to be both accessible through the regular web and ipfs, there isn't much choice; they have to use gateways.
> 
> This would look like this:
> 
>     <img src='https://ipfs.pics/QmdhTuX4V4uAUKotFTFpeHDEkSDvWVGfsvqT5EwtmtnPUW' />
> 
> So:
> 
> * If the website user doesn't have ipfs or the ipfs gateway redirect add-on, they ask ipfs.pics' server for the image *Qmdh[...]PUW*.
> * If they have ipfs and the gateway add-on, the add-on would block the browser request for that image and instead use ipfs to retrieve it.
> 
> # The Problem:
> 
> While this method might work at first, it doesn't scale. If we continue this practice, then the gateway's servers will be overloaded as the ipfs community grows. It would then be unattractive for webmasters to use gateway urls, since they would be slow to load.
> 
> # A Possible Solution:
> 
> Instead of having the user call a gateway server to retrieve an ipfs file, the website server should serve it directly. This would work as follows:
> 
>         [...]
>         
>         <head>
>           <meta name="ipfs-folder" content="/static/ipfs/" />
>         </head>
>         
>         [...]
>         
>         <img src='/static/ipfs/QmdhTuX4V4uAUKotFTFpeHDEkSDvWVGfsvqT5EwtmtnPUW' />
> 
>         [...]
> 
> So:
> 
> * If the website user doesn't have ipfs or the gateway add-on, they simply retrieve */static/ipfs/Qmdh[...]PUW* from the website. This would be the image file located in the */static/ipfs/* folder on the website's server.
> 
> * If they have ipfs and the gateway add-on, the add-on would first notice the meta tag and remember the given folder path. The add-on looks then for urls on the webpage which match the following pattern (assuming our website is example.com): 
>     
>         http://example.com/[Ipfs Folder]/[Ipfs Hash]
> 
>   So in this case:
> 
>         http://example.com/static/ipfs/[Ipfs Hash]
> 
>   The add-on blocks the browser's request for that file, and instead retrieve it from ipfs with the given hash.
> 
> **Result:** No gateway got bothered during the transaction, and it would work for both regular web and ipfs users.

While this might be a bit early (and  probably useless since no website is using it), I was hoping your addon could support this feature.

**Comment by Kubuxu** [comment]
I have different idea: use `web+fs:/ipfs/Qm...AAA` links but check if those links are handled using JS (easy request for an empty directory hash). If they are not handled register local handler that would translate those requests into HTTP requests.

**Comment by RndFooBar** [comment]
> I have different idea: use `web+fs:/ipfs/Qm...AAA` links

    The address wasn’t understood
    
    Firefox doesn’t know how to open this address, because one of the following protocols (web+fs) isn’t associated with any program or is not allowed in this context.

    You might need to install other software to open this address.

This type of link doesn't seem to be understood by browsers, so a normal user without the addon wouldn't be able to download that file.

**Comment by Kubuxu** [comment]
> If they are not handled register local handler that would translate those requests into HTTP requests.

**Comment by Kubuxu** [comment]
See: https://developer.mozilla.org/en-US/docs/Web-based_protocol_handlers

**Comment by RndFooBar** [comment]
Ah, okay! Yeah, that would be great. However:

> check if those links are handled using JS (easy request for an empty directory hash).

This would not work for people using non-default gateway adresses and ports.

**Comment by RndFooBar** [comment]
I suppose you could just use both techniques:

1. You have the `web+fs:/ipfs/Qm...AAA` initially.
1. If those are not supported (because no IPFS or non-default address and/or port), they get replaced by regular HTTP links.
1. If the user has the addon, it blocks the HTTP request, extract the hash, and request the file through IPFS.
1. Else, the browser uses a regular HTTP request

**Comment by Kubuxu** [comment]
If they are not handled, it means that user's browser doesn't support IPFS, in my opinion we should fall black to regular HTTP then (using navigator protocol handlers).

> This would not work for people using non-default gateway adresses and ports.
You check if `web+fs:/ipfs/Qm...AAA` are handled using XHR requests.

See this as a demo:
```
jQuery.get('web+fs:/ipfs/QmUNLLsPACCz1vLxQVkXqqLX5R1X345qqfHbsf67hvA3Nn').always(
    (_, code) => {
        var fsIpfsWorks = (code === "success");
        console.log(fsIpfsWorks);
})
```

Of course we wouldn't use jQuery for that.

The hash in that demo is hash of empty directory that is present in any IPFS installation. We could place some better/smaller hash (as it will download index.html that isn't as small as possible - started issue at https://github.com/ipfs/go-ipfs/issues/3256).

If the `web+fs:/ipfs/...` doesn't work do a fallback to your own static assets as they will be much more efficient in delivery than global gateways.

**Comment by RndFooBar** [comment]
In your demo, you use Web-based protocol handlers which need to be registered in javascript. As far as I understand it, this would look something like this:

    navigator.registerProtocolHandler("web+fs", 
                                      "http://localhost:8080/%s",
                                      "IPFS handler");

This would mean that we would assume that our user uses the default gateway address (localhost) and port (8080) for ipfs. So this wouldn't work for people who have non-default settings. Or do you have a better way of doing this?

**Comment by Kubuxu** [comment]
`web+fs` handler is registered by ipfs enabled browser.

The registration you show would be done as fallback if the browser doesn't support `web+fs`, with address `/static/%s` which would send requests to your server.

**Comment by RndFooBar** [comment]
Okay now I get it (I think)!

You have initialy a `web+fs` url in the webpage.  

* If the user has the addon, the request for the file will be directly redirected through ipfs. 
* If the user doesn't have the addon, the web-based protocol handler first checks whether the browser supports `web+fs` urls. If not, it checks whether ipfs (with default settings) is available through `http://localhost:8080/ipfs/QmU[...]3Nn`
  * If ipfs is avaible, then the file gets downloaded through the `http://localhost:8080/ipfs/$hash`
  * If not, fallback to default HTTP request to the server.

This look indeed better than my proposal.

**Comment by RndFooBar** [comment]
Ok it seems we can't access `http://localhost:8080/` through XHR requests, so I suppose you meant:

* If the user has the addon, the request for the file will be directly redirected through ipfs thanks to the addon. The web-based protocol handler notices this through the XHR request and does nothing.
* If the user doesn't have the addon, the web-based protocol handler notices that `web+fs` urls aren't supported and falls back to default HTTP request to the server.

If that's the case, I would propose a few modifications:
* Rather than `web+fs` urls, shouldn't we use `ipfs:[hash]`urls instead? It seems more intuitive to me.
* Instead of using a XHR request to check whether the urls are supported, why not let the addon set a javascript propriety? I don't know if it's possible but we could use `navigator.ipfsEnabled()`.

**Comment by Kubuxu** [comment]
You might not be able to access `localhost:8080` because CORS allowance was just added to default config in 0.4.3.
It can be enabled with:
```
ipfs config --json Gateway.HTTPHeaders.Access-Control-Allow-Origin '["*"]'
ipfs config --json Gateway.HTTPHeaders.Access-Control-Allow-Methods '["PUT", "GET", "POST"]'
ipfs config --json Gateway.HTTPHeaders.Access-Control-Allow-Headers '["X-Requested-With"]'
```

We have settled on `fs:/` protocol as the best one in long discussion at: https://github.com/ipfs/go-ipfs/issues/1678#issuecomment-157478515

In short terms: the proper way of linking ipfs data is without any URL schema using just `/ipfs/QmAAA...AAA`, for compatibility reasons we want to use some URL schema thus the creation of `fs:/` and as Chrome doesn't allow registration of bare schemas `web+fs:/`.

Using `ipfs:QmAAA...AAA` would break a lot of thins as most websites on ipfs link relative to the root using `/ipfs/QmBBB...BBB` so they work on the gateway.

**Comment by RndFooBar** [comment]
Yeah, that makes sense. And I just noticed that the addon already supports `web+fs`, so [this][1] is already possible. 

Awesome! Thanks a lot, @Kubuxu :).

[1]: https://github.com/lidel/ipfs-firefox-addon/issues/149#issuecomment-249410815

**Comment by Kubuxu** [comment]
Please ping me in an issue or on IRC if you ever do something with it. I will love to see it.

**Comment by RndFooBar** [comment]
Will do!
