### ISSUE TITLE
Verify multihash in the browser

### ISSUE THREAD

**Issue by lidel** [lidel/ipfs-firefox-addon#17]
No matter if it is a public gateway or a custom one, add-on should calculate hash for received data and compare it with the one from URL.

Not sure what should happen when hash does not match.  Probably HTTP Server Error Code (5xx).

Refs.
- Source of idea: https://botbot.me/freenode/ipfs/msg/36342455/
- https://github.com/jbenet/js-multihash
- https://en.wikipedia.org/wiki/List_of_HTTP_status_codes#5xx_Server_Error

**Comment by lidel** [comment]
After giving it some thought I realized that browser addon should just verify if multihash is a valid one  (https://github.com/lidel/ipfs-firefox-addon/commit/595b6f0cd39a7fcfc5e5c8d7b452def5f2a956d0) and that is all. 

There are edge cases when using http-based gateway, for example we can't rehash entire 1GB [video](https://ipfs.io/ipfs/QmTkzDwWqPbnAh5YiV5VwcTLnGdwSNsNTn2aDxdXBFca7D/example#/ipfs/QmQwAP9vFjbCtKvD8RkJdCvPHqLQjZfW7Mqbbqx18zd8j7/videos/readme.md) as it could be fetched via Range Requests. Even downloading big files would be troublesome: we would have to keep data in a buffer until we have all bytes, then rehash, check with multihash, and then accept/throw error. 

Providing a partial support (rehashing asset data only below certain size) would give a false sense of security.

Closing until we can ship js-based IPFS node within addon itself (then it will be implicitly implemented).

**Comment by Kubuxu** [comment]
Maybe option to manually check the hash. This would allow user to confirm that they got the right site.

**Comment by lidel** [comment]
Possible, but I am not sure if worth the effort.  
Manual check is quite easy using already existing tools:

```bash
curl -s https://ipfs.io/ipfs/QmYHNYAaYK5hm3ZhZFx5W9H6xydKDGimjdgJMrMSdnctEm | ipfs add -qn
QmYHNYAaYK5hm3ZhZFx5W9H6xydKDGimjdgJMrMSdnctEm
```

Not sure how  UI for this functionality in browser would look like. 
Right click on image / html and option to "Verify Multihash"?

**Comment by Kubuxu** [comment]
Possibly, but yeah, it might be not worth the effort. If you don't trust your gateway then nor should you trust your browser.

**Comment by ZettaScript** [comment]
This feature would be really useful for web apps, when users don't want to manually download then hash all the files. It seems the simplest solution for trusted web apps.

In case the data doesn't match with the hash, maybe a warning could be displayed, like Firefox does with bad SSL certificates. (and let the user bypass the warning if they want)

**Comment by blavenie** [comment]
> There are edge cases when using http-based gateway, for example we can't rehash entire 1GB video as it could be fetched via Range Requests. Even downloading big files would be troublesome: we would have to keep data in a buffer until we have all bytes, then rehash, compare with provided multihash, and then accept/throw error.

For web apps hosted in IPFS, why not to check if file like [`manifest.json`](https://w3c.github.io/manifest/) or `index.html` exists, then look for a specific attribute to enable the has check ?
If this attribute is present, we check the hash, and then add mark (e.g. a green checkmark icon, or a lock icon) somewhere.

Like this, any IPFS web apps can say "I am compatible for a quick hash check".

e.g. To compare to an existing W3C solution, any HTML file can have optional `integrity` attribute inside a `<script>` tag : 
```html 
  <script src="..." integrity="<hash>" />
```
When set, the browser will check the script source hash before using it.

**Comment by lidel** [comment]
Would be great to use CID in SRI but it requires native IPFS in the browser. Extension won't make it possible, no APIs for that. Maybe one day :)

The CID itself is more than a plain hash of the file. When a file is big it is chunked into blocks and CID is a  hash of the root of a DAG, and user agent  is unable to verify it without learning additional metadata. 

I wrote more details in  https://github.com/ipfs/in-web-browsers/issues/128 (let's continue there)
