### ISSUE TITLE
Refine Regex match (https, gateway. prefix dropped)

### ISSUE THREAD

**Issue by cryptix** [lidel/ipfs-firefox-addon#21]
The 'gateway.'-prefix was obsoleted recently (https://github.com/ipfs/infrastructure/issues/4) and the addon doesn't catch these links yet. HTTPS was also enabled on the public gateways (https://github.com/ipfs/infrastructure/pull/71) these don't match either, I think.

**Comment by lidel** [comment]
Thank you for reporting this. I'll prepare fix soon.

**Comment by lidel** [comment]
FYI I just submitted updated version to Mozilla.
It won't be automatically updated by Firefox until it is reviewed, but one can do it manually at:
https://addons.mozilla.org/en-US/firefox/addon/ipfs-gateway-redirect/versions/?page=1#version-1.0.3

**Comment by lidel** [comment]
That was fast! 1.0.3 just got reviewed :rocket:
