### ISSUE TITLE
When browsing neocities, replace the links with hashes

### ISSUE THREAD

**Issue by jedahan** [lidel/ipfs-firefox-addon#211]
On some neocities profile pages, like https://neocities.org/site/thiscouldbebetter , there are commented out hashes.

Would be cool if the addon allowed us to try and grab the hash for any neocities page and use that instead. Feel free to assign to me.

**Comment by lidel** [comment]
I agree, generally this is what we want, but unfortunately site-specific code does not scale.  😿 

We should handle this in _generic_ way that can be reused on _any site_. 
(I track related discussions in  _https://github.com/lidel/ipfs-firefox-addon/issues/16 Support website hints to reroute HTTP query to IPFS_)

I am closing this ticket -- please contribute to upstream discussions instead:
- _https://github.com/ipfs/notes/issues/92: Recognize IPFS gateways on arbitrary websites_
- _https://github.com/ipfs/notes/issues/104: gateless gate_
   a hint that site assets with names being valid IPFS multihashes can be loaded from IPFS
