### ISSUE TITLE
Allow (un-)pinning of ipns resources.

### ISSUE THREAD

**Issue by donothesitate** [lidel/ipfs-firefox-addon#222]
Allow (un-)pinning of ipns resources via the icon in the same way as ipfs resources.

**Comment by lidel** [comment]
Thank you for reporting this.  

It seems to be possible to pin "current snapshot" of IPNS address via commandline:

```
> ipfs pin add --progress /ipns/ipfs.git.sexy
Fetched/Processed 12 nodes
pinned Qmazvovg6Sic3m9igZMKoAPjkiVZsvbWWc8ZvgjjK1qMss recursively
```
Unpinning is bit tricky, as it does not work for IPNS paths:

```
> ipfs pin rm /ipns/ipfs.git.sexy
Error: invalid 'ipfs ref' path
```

It needs to be unpinned by referring to immutable multihash:

```
> ipfs pin rm Qmazvovg6Sic3m9igZMKoAPjkiVZsvbWWc8ZvgjjK1qMss
unpinned Qmazvovg6Sic3m9igZMKoAPjkiVZsvbWWc8ZvgjjK1qMss
```

That being said, it seems to be doable – it just requires one additional lookup.
I'll look into this.

**Comment by lidel** [comment]
Done. This feature will be present in `v2.0.0alpha3`.

**Comment by lidel** [comment]
[v2.0.0alpha3](https://github.com/lidel/ipfs-firefox-addon/releases/tag/v2.0.0alpha3) is ready for install
