### ISSUE TITLE
Rule to work with NoScript with ABE enabled

### ISSUE THREAD

**Issue by jcline** [lidel/ipfs-firefox-addon#25]
I just started playing with IPFS and noticed that NoScipt blocks objects from loading after the addon does it's magic. I've only tested this rule a little bit, and I'm not sure if it's as secure or inclusive as it should be, but it's worked for me so far.

It'd be nice to have the rule in the documentation at least for users who aren't interested in reading the ABE syntax docs, etc.

In the SYSTEM Rulset I added the first three lines of the following before the existing local deny rule.
```
# Enable IPFS redirect to LOCAL
Site ^http://127.0.0.1:8080/(ipfs|ipns)*
Anonymize

# Prevent Internet sites from requesting LAN resources.
Site LOCAL
Accept from LOCAL
Deny
```

You can find more info about the ABE rule syntax at https://noscript.net/abe/abe_rules.pdf

**Comment by lidel** [comment]
Thanks! I'll add it this week (right now in travel afk).
