### ISSUE TITLE
Test and Adapting to Multiple Processes

### ISSUE THREAD

**Issue by lidel** [lidel/ipfs-firefox-addon#26]
> Dear add-on developer,

> You might have heard the news[1] that future versions of Firefox will run the browser UI separately from web content. This is called Multi-process Firefox (also "Electrolysis" or "e10s")[2], and it is scheduled for release in the first quarter of 2016[3].

> If your add-on code accesses web content directly, using an overlay extension[4], a bootstrapped extension[5], or low-level SDK APIs[6] like window/utils or tabs/utils, then you will probably be affected.

> To minimize the impact on users of your add-ons, we are urging you to test your add-ons[7] for compatibility. You can find documentation on how to make them compatible here[8].

> Starting Nov. 24, 2015, we are available to assist you every Tuesday in the #addons channel on irc.mozilla.org[9]. Click here[10] to see the schedule. Whether you need help testing or making your add-ons compatible, we're here to help!

> Sincerely,
> The Add-ons Team

> [1] https://blog.mozilla.org/addons/2015/08/21/the-future-of-developing-firefox-add-ons/
> [2] https://developer.mozilla.org/en-US/Firefox/Multiprocess_Firefox
> [3] https://wiki.mozilla.org/Electrolysis#Schedule
> [4] https://developer.mozilla.org/en-US/Add-ons/Overlay_Extensions
> [5] https://developer.mozilla.org/en-US/Add-ons/Bootstrapped_extensions
> [6] https://developer.mozilla.org/en-US/Add-ons/SDK/Low-Level_APIs
> [7] https://developer.mozilla.org/en-US/Add-ons/Working_with_multiprocess_Firefox#Testing
> [8] https://developer.mozilla.org/en-US/Add-ons/Working_with_multiprocess_Firefox#Updating_your_code
> [9] irc://irc.mozilla.org/addons
> [10] https://atsay.github.io/e10s_office_hours/

**Comment by the8472** [comment]
I think adding the flag is not sufficient. the protocol handler needs to be registered in content processes too for example.

**Comment by lidel** [comment]
To be honest I just 'assumed' it works natively: got no warnings about slow e10 shims etc.

I tried to confirm it but I was unable to find any good documentation regarding protocol handlers in e10s – do you have any resources in mind?

**Comment by the8472** [comment]
No concrete documentation, but i did some work on greasemonkey and there a protocol handler had to be registered in the child process too to make it work.

I'll do some testing on my end first, maybe a PR will fall out of it too ;)
