### ISSUE TITLE
Linkify ipfs-ish text

### ISSUE THREAD

**Issue by the8472** [lidel/ipfs-firefox-addon#27]
options to turn plain /ipfs/ and ipfs:// text into links and context menu entries to open any highlighted multihash as ipfs links would be nice.

**Comment by lidel** [comment]
Sounds useful  :+1: 

My thinking:
- A new context menu item "Open IPFS resource" visible when there is a text selection that match IPFS resource regex 
- Not sure about turning text into links. I think it could be done, but modifying pages on the fly should be configurable via checkbox on the Preferences screen and probably disabled by default.

If there is no PR with this I'll try to add it in my spare time.. some day. ;-)

**Comment by the8472** [comment]
Yeah, modification of the DOM should be optional.
