### ISSUE TITLE
API port should be configurable

### ISSUE THREAD

**Issue by lidel** [lidel/ipfs-firefox-addon#31]
It should be possible to set it up just like the HTTP Gateway one.

**Comment by jedahan** [comment]
Can you assign this to me? I can get it going this weekend.

**Comment by lidel** [comment]
Sure, feel free to work on it. UX should be similar to:
https://github.com/lidel/ipfs-firefox-addon/blob/master/package.json#L32-L37

PS.  I could only assign to myself in Github GUI (limitation of personal account).
