### ISSUE TITLE
Add support for web+ schema prefix

### ISSUE THREAD

**Issue by Kubuxu** [lidel/ipfs-firefox-addon#36]
As in chrome 'web+' is only allowed prefix for JS schema handling then most sites will be using it (and using JS to rewrite it to gateway). Accepting it and rewriting it to plain fs would be optional solution.

**Comment by lidel** [comment]
Yeah, the [robustness principle](https://en.wikipedia.org/wiki/Robustness_principle) is an important guideline for this add-on.
Due to Chrome's popularity it makes sense to accept yet another protocol variation and normalize it to canonical URIs.

**Comment by Kubuxu** [comment]
Same thing applies to transforming `fs:`, `fs://` and `fs:///` into `fs:/`.

**Comment by lidel** [comment]
Those are already supported. 
(As of version 1.3.1 all custom protocol handlers redirect to URL of the custom HTTP gateway.)

**Comment by lidel** [comment]
Rename the ticket as we [should](https://github.com/ipfs/go-ipfs/issues/1678#issuecomment-163124489)  support chrome prefix for all handlers: `web+fs:`, `web+ipfs:` and `web+ipns:` (with `/` `//` or `///`)

 :)
