### ISSUE TITLE
Move to the "standard" JS linter & formatter

### ISSUE THREAD

**Issue by lidel** [lidel/ipfs-firefox-addon#42]
As of now we use raw ESLint (with some opinionated settings simply copied from my other projects) while [/ipfs/community/js-contribution-guidelines](https://github.com/ipfs/community/blob/master/js-contribution-guidelines.md) ([#59](https://github.com/ipfs/community/issues/59)) suggests http://standardjs.com to be used across IPFS-related projects, where possible.

I think it may be beneficial to switch and enforce it via [standard-format](https://github.com/maxogden/standard-format) as a pre-commit hook.

(I did a dry run and the main change from current style is the removal of semicolons.)

I'll leave this open for a week or so and if there will be no cons raised – commit the change.

**Comment by jedahan** [comment]
:+1:
