### ISSUE TITLE
False-positive href rewrites (when "Extended IPFS link support" is enabled)

### ISSUE THREAD

**Issue by Kubuxu** [lidel/ipfs-firefox-addon#43]
It breaks on ipfs's github as it starts with `/ipfs/...`.

On solution would be to push ipfs/notes#92 forward and resolve it in case of `/ipfs/...` or `/ipns/...` to confirm if redirection to local gateway should take place.

**Comment by lidel** [comment]
Yup, will need to stop doing regex-based rewrites due to false-positives like this one.
