### ISSUE TITLE
Sites under public gateways list can't make XHR request

### ISSUE THREAD

**Issue by Kubuxu** [lidel/ipfs-firefox-addon#45]
I have site http://bin.kubuxu.ovh, its A records are same as ipfs.io. If I add it to the public gateways list XHR request to `/ipfs/[some hash]` fails because it is rerouted to local gateway which breaks AJAX somehow. In my case solution would be to redirect site to: `http://localhost:8080/ipns/bin.kubuxu.ovh/` then XHR will be allowed to fetch data from `/ipfs/...`.

The solution for this problem might be tricky as for example http://ipfs.pics has to make requests to severs itself (it does not have dnslink).

**Comment by lidel** [comment]
Indeed: I've  put a breakpoint in the `error` callback of `$.ajax` request and the `err.status()` returns `rejected` (and not much beside that). 

We probably need to dig into jQuery internals to understand this better,
perhaps XHR requests require some additional logic.

**Comment by Kubuxu** [comment]
Also the request is not even sent (I Wireshark'ed it).

**Comment by lidel** [comment]
Ok, I (probably) know what is happening. 

> ![2016-01-15-184300_640x117_scrot](https://cloud.githubusercontent.com/assets/157609/12360464/7cdddb6e-bbb8-11e5-9240-c8a99ff62dbe.png)

Doing XHR request with  gateway redirect enabled is effectively doing cross-domain scripting.  

Firefox protects users from [XSS](https://en.wikipedia.org/wiki/Cross-site_scripting) and executes requests like this only if target server is explicitly configured to accept them. It is indicated via [CORS](https://en.wikipedia.org/wiki/Cross-origin_resource_sharing) headers and what Firefox does here it to issue `OPTIONS` request to the gateway to check for them.

I have go-ipfs v0.3.11-dev and it does not support `OPTIONS` by default:

    > curl -X OPTIONS http://127.0.0.1:8080/ipfs/QmRqoVq1G9pL7hyLB2EGi5mndRTQv7tKfFXPRUsSbpHqfK
    Method OPTIONS not allowed: read only access


What is more, CORS headers are also missing in gateway responses:

```text
> curl -X HEAD -I http://127.0.0.1:8080/ipfs/QmRqoVq1G9pL7hyLB2EGi5mndRTQv7tKfFXPRUsSbpHqfK
HTTP/1.1 200 OK
Accept-Ranges: bytes
Access-Control-Allow-Headers: X-Stream-Output, X-Chunked-Output
Access-Control-Expose-Headers: X-Stream-Output, X-Chunked-Output
Cache-Control: public, max-age=29030400
Content-Length: 624
Content-Type: text/plain; charset=utf-8
Etag: QmRqoVq1G9pL7hyLB2EGi5mndRTQv7tKfFXPRUsSbpHqfK
Last-Modified: Thu, 01 Jan 1970 00:00:01 GMT
Suborigin: QmRqoVq1G9pL7hyLB2EGi5mndRTQv7tKfFXPRUsSbpHqfK
X-Ipfs-Path: /ipfs/QmRqoVq1G9pL7hyLB2EGi5mndRTQv7tKfFXPRUsSbpHqfK
Date: Fri, 15 Jan 2016 18:05:26 GMT
```


It is a known issue and was mentioned in https://github.com/ipfs/go-ipfs/pull/1215#issuecomment-113980145 and https://github.com/ipfs/go-ipfs/issues/934#issuecomment-87410776.

**So it is not a bug in Addon/Firefox, but a default behaviour of IPFS Gateway.**  :anguished: 

Running writable gateway with CORS headers is supported by go-ipfs, but you need to enable it manually: 

    ipfs config --json Gateway.HTTPHeaders.Access-Control-Allow-Methods '["PUT,GET,POST,OPTIONS"]'
    ipfs config --json Gateway.HTTPHeaders.Access-Control-Allow-Origin '["*"]'
    ipfs config --json Gateway.Writable true

Then restart the daemon.

Sadly, `OPTION` still does not work:

> curl -X OPTIONS http://127.0.0.1:8080/ipfs/QmRqoVq1G9pL7hyLB2EGi5mndRTQv7tKfFXPRUsSbpHqfK

    18:45:57.364 ERROR core/serve: Method OPTIONS not allowed: bad request for /ipfs/QmRqoVq1G9pL7hyLB2EGi5mndRTQv7tKfFXPRUsSbpHqfK gateway_handler.go:94


I'll pursue it further, perhaps we need add `OPTIONS` to [gateway_handler.go:80](https://github.com/ipfs/go-ipfs/blob/04914ace6e63b9e980f5fa22c47bf7027d6a2d52/core/corehttp/gateway_handler.go#L80).

**Comment by lgierth** [comment]
> I'll pursue it further, perhaps we need add OPTIONS to gateway_handler.go:80.

:+1:

**Comment by lidel** [comment]
[OPTIONS support fixed upstream](https://github.com/ipfs/go-ipfs/issues/2232).
A related discussion about CORS/XHR support for API is continued in https://github.com/ipfs/go-ipfs/issues/2239
