### ISSUE TITLE
Automatic Mode

### ISSUE THREAD

**Issue by Kubuxu** [lidel/ipfs-firefox-addon#50]
Disabling gateway redirection if IPFS is non functional would be nice feature.

Local gateway redirection could be disabled if:
* `ipfs.io` responses to `/version` (we have connection with alternative) and
* local gateway has no peers in swarm

**Comment by lidel** [comment]
I think we could do it both ways and have an "Automatic Mode":
A checkbox on the Preferences screen would enable polling of `/api/v0/swarm/peers` periodically (perhaps interval  could be customized too) and if list of peers is >0 then we automatically enable redirect to custom gateway. If response is negative, then redirect is disabled.
