### ISSUE TITLE
With atomatic mode enabled it is impossible to maually disable the redirect

### ISSUE THREAD

**Issue by Kubuxu** [lidel/ipfs-firefox-addon#62]
I click: Disable gateway redirect, it comes back to on.

I don't know if there is good way to make it user controllable but still automatic.

**Comment by lidel** [comment]
Perhaps we should just disable Automatic Mode when user manually disables redirect? 
I guess that is the user's intention anyway.

**Comment by lidel** [comment]
Will ship a fix in 1.5.2
