### ISSUE TITLE
Add h.ipfs.io to public gateways list.

### ISSUE THREAD

**Issue by Kubuxu** [lidel/ipfs-firefox-addon#63]
It is a Hyperboria network gateway.

**Comment by lidel** [comment]
Oh, this is new to me. Are there any issues related to Hyperboria integration?

I am not sure if we should put it on the list: it seems to only have  `AAAA`  records  (ipv6) and may confuse users who don't use Hyperboria and try to visit page while on ipv4-only link.

**Comment by Kubuxu** [comment]
It just won't work for them (or even for people having IPv6 but not being in Hyperboria network). It is just that it is not redirecting to local from it by default but as Hyperboria is not use by many I don't really see a reason to add it there by default.
