### ISSUE TITLE
With DNS Lookup enabled sites that are gateways are redirecting incorrectly.

### ISSUE THREAD

**Issue by Kubuxu** [lidel/ipfs-firefox-addon#64]
It happened for me with h.ipfs.io but I think you can reproduce it by removing ipfs.io from public gateways list and visiting link like: https://ipfs.io/ipfs/QmTkzDwWqPbnAh5YiV5VwcTLnGdwSNsNTn2aDxdXBFca7D/

The redirect will place you at `localhost:8080/ipns/ipfs.io/ipfs/QmTkzDwWqPbnAh5YiV5VwcTLnGdwSNsNTn2aDxdXBFca7D/`

I don't know how to fix it right.

**Comment by lidel** [comment]
Good catch. I think we could be smarter about detecting IPFS paths (probably need to do https://github.com/lidel/ipfs-firefox-addon/issues/47 for that) and remove `/ipns/ipfs.io` prefix in such situations.

**Comment by lidel** [comment]
Will ship a fix in 1.5.2
