### ISSUE TITLE
Using DNS Lookup crashes with RES

### ISSUE THREAD

**Issue by Kubuxu** [lidel/ipfs-firefox-addon#65]
Steps to produce:
1. Install Reddit Enchantment Suite
2. Install IPFS Redirect
2. Restart FF
3. Open Reddit and try opening extending some image.
4. Crash.

**Comment by lidel** [comment]
I was unable to reproduce. Could you provide a reddit link which triggers the crash for you?

**Comment by Kubuxu** [comment]
It is not a link, it is action of opening a image (RES adds option to open image without going out of the reddit). DNS entry can't be cached.

**Comment by lidel** [comment]
Yup, it seems to work for me on random image (https://goo.gl/3yCzSj – IPFS was up and dnslookup active, image opens fine).  

Does it work for you? Perhaps the problem is caused by something else?

**Comment by lidel** [comment]
Any update on this? [;-)](https://ipfs.io/ipfs/QmYHNYAaYK5hm3ZhZFx5W9H6xydKDGimjdgJMrMSdnctEm)

**Comment by Kubuxu** [comment]
I can't reproduce it not. I will reopen if it happens again.

**Comment by Kubuxu** [comment]
Just was able to reproduce. It has to be a `.gifv`, cache can't be populated. Try restarting FF, opening https://www.reddit.com/r/aww/comments/452pcx/our_puppy_wilson_meeting_a_cat_for_the_first_time/ and opening the gifv with RES.

**Comment by lidel** [comment]
Tried a few times (only two addons installed, fresh profile), works fine for me:

> 
![2016-02-10-225645_676x519_scrot](https://cloud.githubusercontent.com/assets/157609/12963201/93443ede-d049-11e5-8ea1-36c0c3a6206d.png)

Perhaps there is a clash with other addon due to synchronous dnslink  lookup. Let's wait and see if https://github.com/lidel/ipfs-firefox-addon/issues/69  solves the problem.

Int he meantime, try to get some debug information from Browser Console from the moment of crash (try running in terminal etc). 
Does Firefox segfaults?

**Comment by Kubuxu** [comment]
I am running Windows right now, if I was on Linux I would just `gdb` it.

Will check.

**Comment by Kubuxu** [comment]
In console I was able to get:
```
Assertion failure: !mDoingStableStates, at c:/builds/moz2_slave/rel-m-beta-w32_bld-00000000000/build/xpcom/base/CycleCollectedJSRuntime.cpp:1057
```
FF45b4

**Comment by lidel** [comment]
Seems that it is a bug in Firefox itself (`HTMLMediaElement`)
Someone run into the same problem with NoScript addon:

- https://bugzilla.mozilla.org/show_bug.cgi?id=1235183 (as of this moment, still not fixed)

**Comment by lidel** [comment]
@Kubuxu please [update to v1.5.4](https://addons.mozilla.org/en-US/firefox/addon/ipfs-gateway-redirect/versions/1.5.4), perhaps asynchronous lookup helped with this Firefox bug. 
If not, I am afraid you need to wait for [upstream fix](https://bugzilla.mozilla.org/show_bug.cgi?id=1235183).
