### ISSUE TITLE
Minimize use of custom protocol handler 

### ISSUE THREAD

**Issue by lidel** [lidel/ipfs-firefox-addon#7]
While having thesupport for 'virtual' URI like `ipfs:QmTkzDwWqPbnAh5YiV5VwcTLnGdwSNsNTn2aDxdXBFca7D` is handy and provides us with nice abstraction, we should always redirect from virtual protocol to real URI from a HTTP gateway.

Gist is this: always display real URI in address bar (but also [provide an easy way of obtaining IPFS links](https://github.com/lidel/ipfs-firefox-addon/issues/4)).

**Comment by the8472** [comment]
could you elaborate on the security problems that lead to this change?

It would be nice if we could find a way around them.

**Comment by lidel** [comment]
I think my rationale back then was that we should not "fake" /ipfs/ URLs in address bar. 

As of today, Firefox does not provide native IPFS support by itself nor via addon.
We use HTTP gateway and user should see gateway host name when looking at the address bar.

When things like [js-ipfs](https://github.com/ipfs/js-ipfs) are mature enough, we could provide native IPFS support, and then we could legitimately display raw IPFS paths like  `/ipfs/QmTAsnXoWmLZQEpvyZscrReFzqxP3pvULfGVgpJuayrp1w` in the address bar.

**Comment by the8472** [comment]
Hrm, issue #3 made it sound like there were some security issues.

I'd like "fake" `ipfs://` in the url bar when running a custom gateway. From my POV it's basically just shifting the loading from firefox to an external process under my control.

Would it be reasonable to make this optional behavior?

**Comment by lidel** [comment]
#3 was a false-positive security error that was a result of mixing assets using "fake" and "real" URLs. It should be possible to fix it by having "fake" URLs everywhere, but I was not motivated enough to pursue this charade at the time :-)

FYI some time after #3 IPFS community had rather long discussions about "canonical" and "legacy" IPFS addressees [here](https://github.com/ipfs/go-ipfs/issues/1678#issuecomment-139339562) and [here](https://github.com/lidel/ipfs-firefox-addon/issues/16#issuecomment-92343901) which can be summarized by [this quote from #16](https://github.com/lidel/ipfs-firefox-addon/issues/16#issuecomment-92343901) about path-like "canonical ones":

> [..] "ipfs links" should be exactly the same in both the Web, and UNIX. meaning: `/ipfs/<hash>/<path>`, NOT `ipfs://<hash>/<path>` (explicitly disobeying the scheme that the W3C insists on).

and "legacy" ones in form of `ipfs:[/]*` and `fs:[/]*`.

So to keep this short:

- I am okay with someone implementing "fake" URL (probably best is to use native `/ipfs/<hash>`) in the address bar as an optional behaviour (enabled via checkbox on the preferences screen).
