### ISSUE TITLE
Origin policy for fs: URIs

### ISSUE THREAD

**Issue by the8472** [lidel/ipfs-firefox-addon#71]
According to [mozilla bug 1247529#c16](https://bugzilla.mozilla.org/show_bug.cgi?id=1247529#c16) it should be possible to give individual uris custom origins, similar to chrome's suborigins.

The question is what the origin policy should be for various kinds of paths

**Comment by lidel** [comment]
I don't see a lot of options here.
The closes thing to an origin would probably be the first segment after `/ip(f|n)s/` (hash or fqdn).

As for implementation.. aren't you afraid when you read things like:

> Note that these APIs aren't guaranteed to stay stable.

Remember that we will need to [stop using XUL/XPCOM  soon](https://blog.mozilla.org/addons/2015/08/21/the-future-of-developing-firefox-add-ons/).

I strongly believe our effort should go into designing/requesting any missing [WebExtensions APIs](https://github.com/lidel/ipfs-firefox-addon/issues/20), as it is the only thing that will reliably work in future.

**Comment by Kubuxu** [comment]
I also agree on first segment after `/ip(f|n)s/`.
Also we should insert our own `localStorage` on per origin basis.

**Comment by the8472** [comment]
> aren't you afraid when you read things like:
>>    Note that these APIs aren't guaranteed to stay stable.

It should be easy enough to isolate this into a separate module and have tests for it. Add CI running against nightly and there would be enough early warning if they break something. And it's not like they aren't breaking stuff every now and then anyway.

>  I strongly believe our effort should go into designing/requesting any missing WebExtensions APIs, as it is the only thing that will reliably work in future. 

I think it's important to demonstrate a current use of such APIs. Also, an alternative plan to *beg for APIs* will be [write your own webextension APIs, allow mozilla to adopt them later](https://bugzilla.mozilla.org/show_bug.cgi?id=1215306)

**Comment by lidel** [comment]
Thanks, it makes more sense to me now.  PR is welcome.

**Comment by lidel** [comment]
Quick brain dump or related resources:
- [Suborigins  Spec: W3C Editor’s Draft](https://w3c.github.io/webappsec-suborigins/)
- go-ipfs gateway already returns HTTP `Suborigin` header with every response for `/ipfs/` resources: [core/corehttp/gateway_handler.go#L176](https://github.com/ipfs/go-ipfs/blob/eaa4ff0ce9e685f37cbd9eb3a38cf4ddacab4381/core/corehttp/gateway_handler.go#L176).
- [Related discussion about Suborigin support in go-ipfs / Chrome](https://github.com/ipfs/go-ipfs/issues/651)
- Firefox did not start any work yet :cry:  [Bug #1231225 - Suborigins namespace mechanism](https://bugzilla.mozilla.org/show_bug.cgi?id=1231225)

**Comment by the8472** [comment]
I think suborigins are useless in this context because they are only *sub-* in nature. `fs:/` URIs have no origin and thus get random UUID origins as per [RFC rfc6454](https://tools.ietf.org/html/rfc6454#page-10)

Putting any fixed suborigin under a random top origin won't win us anything, since the combination of both is still random.

**Comment by lidel** [comment]
Yes, suborigins are a half measure that "works" as long user keeps using the same gateway.

I mentioned it because there will probably be no other option than to use Suborigins under Chrome/Blink.  It will be the lowest common denominator and I feel we want to model our origin policy to be compatible with Suborigin header (and additionally gateway-agnostic).

>If uri-scheme is "file", the implementation MAY return an implementation-defined value.

Cool, so we probably could bend it a bit and apply this to `fs:` and instead of `(uri-scheme, uri-host, uri-port)` use `(uri-scheme, (ipfs|ipns), (multihash|ipns-name))`

**Comment by lidel** [comment]
This issue is outdated. Closing.
A more broad discussion will continue in https://github.com/ipfs/in-web-browsers/issues/6
