### ISSUE TITLE
no-cookies, no-cache-validate channels for /ipfs/ paths?

### ISSUE THREAD

**Issue by the8472** [lidel/ipfs-firefox-addon#72]
As noted in 4296e7dd8af06ffe3a053c74fe43d0a148415729 setting `nsIRequest.LOAD_ANONYMOUS` and `VALIDATE_NEVER` on requests to gateways might make sense.

Cookies set while explicitly browsing *http://gateway.tld/foo/bar* pages shouldn't have anything to do with the gateway services themselves, and there's no meaningful way to expose them to content anyway.
And /ipfs/ paths should be forever stable, so we can be pretty sure that they don't need any cache validation, no matter what the server says.

**Comment by lidel** [comment]
- I agree on `nsIRequest.VALIDATE_NEVER` for `/ipfs/`, it would not hurt to set it.
- `nsIRequest.LOAD_ANONYMOUS`: I am bit worried that blocking cookies may cause some unknown consequences, eg. break some static apps that use them for simple things like storing theme/font size preference, game saves etc.    
   Question: does it also block [`localStorage`](https://developer.mozilla.org/en-US/docs/Web/API/Storage/LocalStorage)?

**Comment by Kubuxu** [comment]
`localStorage` is disabled where there is no authority part in URI.

**Comment by lidel** [comment]
After giving it some thought I think would be ok to enable `nsIRequest.LOAD_ANONYMOUS` when `fs:` is set as a target protocol handler  (https://github.com/lidel/ipfs-firefox-addon/pull/70).
Even if we set `fs:` as a default, there will be an option to disable it and fallback to http-based URLs, in which cookies and localStorage work in old school way. 

This should be good enough for now, at least until we have https://github.com/lidel/ipfs-firefox-addon/issues/71 sorted out.
