### ISSUE TITLE
CI against nightly

### ISSUE THREAD

**Issue by the8472** [lidel/ipfs-firefox-addon#73]
I think it's important to have early warnings in case something breaks due to an upcoming change.

And personally I develop mostly against nightly, so having a delta of "passes on nightly, breaks on release" would be helpful to isolate problems.

**Comment by lidel** [comment]
I agree, will add it soon.

**Comment by lidel** [comment]
Added nightly build. It is marked as "required to pass":
https://travis-ci.org/lidel/ipfs-firefox-addon
