### ISSUE TITLE
NS_ERROR_FAILURE: nsIPrincipal.origin

### ISSUE THREAD

**Issue by lidel** [lidel/ipfs-firefox-addon#77]
Having `prefs.fsUris=true` occasionally [produces](https://travis-ci.org/lidel/ipfs-firefox-addon/jobs/109184172#L494):
```
console.log: ipfs-firefox-addon: [JavaScript Error: "NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIPrincipal.origin]" {file: "resource://app/modules/sessionstore/SessionStorage.jsm" line: 78}]
```

@the8472 are you familiar with the origin of this error?  It seems to be related to https://github.com/lidel/ipfs-firefox-addon/issues/71

**Comment by the8472** [comment]
It basically means the session manager doesn't like pages without origin, in principle it's a [bug in firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=1247529), but implementing #71 would also prevent that.

**Comment by lidel** [comment]
Ok, so basically session storage is disabled and we have this bit verbose error in log, but no other side-effects. 
I feel we can close this as a kind-of duplicate of #71
