### ISSUE TITLE
CORS regression with FF 43

### ISSUE THREAD

**Issue by lidel** [lidel/ipfs-firefox-addon#80]
Seems we have a https://github.com/lidel/ipfs-firefox-addon/issues/3  [regression with FF 43](https://travis-ci.org/lidel/ipfs-firefox-addon/jobs/109184174#L525) detected by [test/test-canonical-fs-uris.js](https://github.com/lidel/ipfs-firefox-addon/blob/9ed741cc5ec0c7a215c09d0044eba2dfda52a085/test/test-canonical-fs-uris.js#L51):

```
.........console.log: ipfs-firefox-addon: [JavaScript Warning: "Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://ipfs.io/ipfs/QmSrCRJmzE4zE1nAfWPbzVfanKQNBhp7ZWmMnEdbiLvYNh/sample.md. (Reason: missing token 'x-requested-with' in CORS header 'Access-Control-Allow-Headers' from CORS preflight channel)."]
```

@the8472 do you think it is worth investigating?  The error is present only under FF 43.
If it is a bug in older FF version, we could just drop support for  FF <44 in v1.5.5

**Comment by the8472** [comment]
It should only affect the canonical URIs feature, so we could just turn it off for FF43 if no fix can be found?

**Comment by lidel** [comment]
Ok, story time  :last_quarter_moon_with_face: 

I tried to replicate the error locally under FF 43 – got the same results, but it turned  out to  be caused by the v04x gateway not having  `Access-Control-Allow-Headers` set up:

```
> curl -Ik -X OPTIONS "https://v04x.ipfs.io/ipfs/QmSrCRJmzE4zE1nAfWPbzVfanKQNBhp7ZWmMnEdbiLvYNh/sample.md"         
HTTP/1.1 200 OK
Date: Mon, 15 Feb 2016 21:37:36 GMT
Content-Type: text/plain; charset=utf-8
Content-Length: 0
Connection: keep-alive
Access-Control-Allow-Origin: *
Strict-Transport-Security: max-age=15768000
```

I've set up go-ipfs 0.4.0-dev locally (0.3.0 does not support HTTP `OPTIONS` request type) and added CORS-related headers: 

```
ipfs config --json Gateway.HTTPHeaders.Access-Control-Allow-Methods '["PUT", "GET", "POST"]'
ipfs config --json Gateway.HTTPHeaders.Access-Control-Allow-Origin '["*"]'
ipfs config --json Gateway.HTTPHeaders.Access-Control-Allow-Headers '["X-Requested-With"]'
```

Loading `fs:/ipfs/QmSrCRJmzE4zE1nAfWPbzVfanKQNBhp7ZWmMnEdbiLvYNh/mdown#sample.md` was a success.

I think  FF 43 was more strict than latest versions and refuses to send XHR when  `X-Requested-With` is missing in response to a [preflight check](https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS#Preflighted_requests), but when the header is added to the gateway, it works fine. 

So.. no bug per se, closing.
