### ISSUE TITLE
DNS Lookup redirect doesn't work for IPNS

### ISSUE THREAD

**Issue by Kubuxu** [lidel/ipfs-firefox-addon#82]
Try: http://ipns.kubuxu.ovh or http://www.kubuxu.ovh

**Comment by lidel** [comment]
I am running go-ipfs `0.4.0-dev-d3b467f` and HTTP API used by the addon for dns lookups does not return IPFS paths for your domains:

```
> curl http://127.0.0.1:8080/api/v0/dns/www.kubuxu.ovh
{"Message":"Could not resolve name (recursion limit exceeded).","Code":0}

> dig +short TXT ipns.kubuxu.ovh @8.8.8.8
"dnslink=/ipns/QmdKbeXoXnMbPDfLsAFPGZDJ41bQuRNKALQSydJ66k1FfH/"
```
```
> curl http://127.0.0.1:8080/api/v0/dns/ipns.kubuxu.ovh
{"Message":"Could not resolve name (recursion limit exceeded).","Code":0}

> dig +short TXT ipns.kubuxu.ovh @8.8.8.8
"dnslink=/ipns/QmdKbeXoXnMbPDfLsAFPGZDJ41bQuRNKALQSydJ66k1FfH/"
```

Compare it with working ones (both new and old syntax work fine):

```
> curl http://127.0.0.1:8080/api/v0/dns/ipfs.git.sexy
{"Path":"/ipfs/QmVyS3iAy7mvDA2HqQWm2aqZDcGDH3bCRLFkEutfBWNBqN"}

> dig +short TXT ipfs.git.sexy @8.8.8.8
"QmVyS3iAy7mvDA2HqQWm2aqZDcGDH3bCRLFkEutfBWNBqN"

> curl http://127.0.0.1:8080/api/v0/dns/ipfs.io
{"Path":"/ipfs/QmNu7McSMSi3vp6avTZrgW6MKdgeDkGjJGY6W5zPjnh9Xg"}

> dig +short TXT ipfs.io @8.8.8.8
"dnslink=/ipfs/QmNu7McSMSi3vp6avTZrgW6MKdgeDkGjJGY6W5zPjnh9Xg"
```

Not sure what is the problem, 
the only difference I see is `/` at the end of your dnslink definitions.  

Try removing it. If it does not help, close this one and fill an issue at [go-ipfs/issues](https://github.com/ipfs/go-ipfs/issues).

**Comment by lidel** [comment]
I closed it, but out of curiosity, what was the problem, @Kubuxu ?

**Comment by Kubuxu** [comment]
I didn't figure it out, it just started working, possibly my DNS didn't propagate or was cached.

**Comment by lockedshadow** [comment]
I'm not sure, but it seems that this issue is related to https://github.com/ipfs/go-ipfs/issues/1350.
At least, redirecting doesn't work for me too, if the TXT-record contains IPNS link.
