### ISSUE TITLE
Text in pop-up box irritable in case of some GTK themes.

### ISSUE THREAD

**Issue by Kubuxu** [lidel/ipfs-firefox-addon#84]
Probably background or text colour has to be set.
https://ipfs.io/ipfs/QmTxMbykSQrcGQzVhquVCtDPGBRd3chPEDpvnZ7RGoriNp/screencap.2016-02-18T11:57:53Z.png

**Comment by lidel** [comment]
@Kubuxu  what is the name of this theme?

**Comment by Kubuxu** [comment]
Numix Solarized

**Comment by lidel** [comment]
Fixed: 
> 
![2016-02-19-184342_2560x1080_scrot-fs8](https://cloud.githubusercontent.com/assets/157609/13183848/000eeb90-d739-11e5-8345-7be86afcfdf4.png)
