### ISSUE TITLE
Drop file with mouse into drop zone WebUI - files does nothing

### ISSUE THREAD

**Issue by iav** [lidel/ipfs-firefox-addon#89]
Drop file with mouse into drop zone WebUI - files does nothing.
Windows 7, firefox 45b2

**Comment by lidel** [comment]
I was unable to replicate under go-ipfs 0.3.11 with Windows 7 and FF 44.0.2.
Which go-ipfs version are you using?

**Comment by iav** [comment]
1.5.5.
Seems after I add one file by pressing file button and choose file with chooser, drop zode start to work, and now it working.

**Comment by iav** [comment]
Sorry for disturbance.

**Comment by lidel** [comment]
Cool, if you find any other issues related to WebUI, 
https://github.com/ipfs/webui/issues may be a better place :)

**Comment by iav** [comment]
Oh! Thank you. It's not clean webui inside addon not part of addon.
