### ISSUE TITLE
Error 0x804b000a (MALFORMED_URI) when customGatewayHost pref is empty

### ISSUE THREAD

**Issue by deltab** [lidel/ipfs-firefox-addon#93]
On browser startup, if the custom gateway host is set to the empty string, it causes URI construction in gateways.js line 43 to fail with the following error logged multiple times:

Mar 19 22:24:22 console.error: ipfs-firefox-addon: 
Mar 19 22:24:22 Object
Mar 19 22:24:22     - message = Component returned failure code: 0x804b000a (NS_ERROR_MALFORMED_URI) [nsIIOService.newURI]
Mar 19 22:24:22     - fileName = undefined
Mar 19 22:24:22     - lineNumber = 43
Mar 19 22:24:22     - stack = @undefined:43:NaN|f@resource://ipfs-firefox-addon-at-lidel-dot-org/lib/gateways.js:43:24|@resource://ipfs-firefox-addon-at-lidel-dot-org/lib/gateways.js:37:28|@resource://ipfs-firefox-addon-at-lidel-dot-org/lib/gui.js:7:12|@resource://ipfs-firefox-addon-at-lidel-dot-org/lib/main.js:3:1|run@resource://gre/modules/commonjs/sdk/addon/runner.js:147:19|startup/</<@resource://gre/modules/commonjs/sdk/addon/runner.js:87:9|Handler.prototype.process@resource://gre/modules/Promise-backend.js:933:23|this.PromiseWalker.walkerLoop@resource://gre/modules/Promise-backend.js:812:7|this.PromiseWalker.scheduleWalkerLoop/<@resource://gre/modules/Promise-backend.js:746:1|
Mar 19 22:24:22     - toString = () => toString

This happens even though useCustomGateway is off.

extensions.ipfs-firefox-addon@lidel.org.customGatewayHost;
extensions.ipfs-firefox-addon@lidel.org.useCustomGateway;false
extensions.ipfs-firefox-addon@lidel.org.sdk.load.reason;startup
extensions.ipfs-firefox-addon@lidel.org.sdk.version;1.5.5
extensions.ipfs-firefox-addon@lidel.org.fsUris;true

**Comment by lidel** [comment]
Not sure what is the best fix from the UX perspective. 
There is a lot of code that rely on this being valid. 

For now I decided to replace empty host with `127.0.0.1`.  
The fix will be in 1.5.6, but feel free to reopen if  it is not enough.
