### ISSUE TITLE
Web Ui opens but seems unconnected with gateway not on localhost

### ISSUE THREAD

**Issue by iav** [lidel/ipfs-firefox-addon#97]
Not sure it is a bug.
I set ipfs daemon binary to my Raspberry Pi. Set only ipfs binary, no webui tree.
Already have firefox addon previously worked with local ipfs setup.
Now i just change a custom gateway host in addon settings.
Seems ipfs redirection works itself, and number of peers on icons looks real. But all content of webui page seems like unconnected: all fields "empty", "unknown" or just blank.

**Comment by lidel** [comment]
Seems to be WebUI issue (outside of the scope of this addon). Is it in any way related to  https://github.com/ipfs/webui/issues/157 ?

Are there any errors in Browser Console? (CORS/JS ones)

**Comment by iav** [comment]
Notning in browser console.
ipfs daemon restart does nothing.

Please, tell me - should I install webgui on router, or addon should be enough?

**Comment by lidel** [comment]
WebUI is a part of go-ipfs binary, so as long you have ipfs daemon running it should be present.
To be more exact: when you open `http://<rpi-ip>:5001/webui` the WebUI is fetched from IPFS using a hash that is hardcoded in the binary/config file. 

From what you described, it seems that HTML is fetched ok, but it does not fetch realtime data from the running daemon (via JSON API). Perhaps the IP should be set in config somewhere.

WebUI developers should be able to help in diagnosing the source of your problem.
   
They may not watch this repo, so you need to create a new Issue at  https://github.com/ipfs/webui/issues 
(remember to link to this issue + include go-ipfs version and IPs you are using in your setup)
