### ISSUE TITLE
Toolbar button does not display in private browsing

### ISSUE THREAD

**Issue by chungy** [lidel/ipfs-firefox-addon#98]
The extension otherwise functions, such as redirecting public gateways to the localhost one, but there's no button displayed to copy a public link or open the WebUI.

This also affects Firefox when the browser is configured to "Never remember history" -- in which case, the button never displays at all.

**Comment by lidel** [comment]
I agree, it does not make much sense to hide UI while the low level redirect is active.
The button should be visible in private browsing, as  it does not decrease privacy in any way.

Will fix in next version.

Ref. https://developer.mozilla.org/en-US/Add-ons/SDK/High-Level_APIs/private-browsing
